[versions]
junit = "5.12.1"
junit-platform = "1.12.1"
kafka = "3.9.1"
protobuf = "4.33.5"
protobuf-plugin = "0.9.5"
spring-boot = "4.0.0"
testcontainers = "1.20.6"

[libraries]
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-kafka = { module = "org.testcontainers:kafka" }

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
